name: Create Beta

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04 # [self-hosted, ptg]
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -f DockerfileBeta -t telegram-build .
      - name: Build app
        run: docker run --rm -v "$PWD":/home/source telegram-build #--cpus="3.5" -m 6000M telegram-build
      - name: Print Hash
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: sha256sum TMessagesProj/build/outputs/apk/afat/debug/app.apk
      - name: Save artifact
        uses: actions/upload-artifact@master
        with:
          name: PTelegramBeta-v448.apk
          path: TMessagesProj/build/outputs/apk/afat/debug/app.apk
      - name: Create cleanup request
        run: touch delete_request
